spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/fortibank
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate: 
      ddl-auto: update